tensorflow-tensorflow, 0, 2021-11-05 16:53:33 , HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/tensorflow/tensorflow (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))网络连接失败: user_name: tensorflowowner_name: tensorflow
